### ISSUE TITLE
Performance compared to original paper

### ISSUE THREAD

**Issue by spongepuddingg** [RohJiHyun/Deformable-Shape-Completion-with-Graph-Convolutional-Autoencoders-public#1]
This is a very valuable repo! 
Great work reproducing the approach from the "Deformable Shape Completion with Graph Convolutional Autoencoders" paper. 
I'm working on some related works about 3D shape learning and I'm curous to know if the results from the reproduced model comparable to the results reported in the original paper?

**Comment by fabyday** [comment]
hello, liuyuex97.
not yet update readme file about performance and result image. but it works well. like that paper.
my code completed test to only face data, not body data.


and if you want to test other shape data like a body and something else, 
you need to notice that this code is hard coding. modifying shape before the test you want.(it is located in [model/modelwrapper2.py](https://github.com/RohJiHyun/Deformable-Shape-Completion-with-Graph-Convolutional-Autoencoders-public/blob/master/model/modelwrapper2.py "code"))

I mean unstable yet.
becuase I want to see performance about paper, as fast as possible.

**Comment by spongepuddingg** [comment]
Thanks for your thorough explanation and your note about the hard coded layer definitions. I am personally limited by computation capacity due to Covid situation so it is great to know that the results can be reproduced before running anything.

**Comment by fabyday** [comment]
I'm glad it was helpful. :)
