### ISSUE TITLE
Decoding concept 

### ISSUE THREAD

**Issue by ahariri13** [RohJiHyun/Deformable-Shape-Completion-with-Graph-Convolutional-Autoencoders-public#2]
Hello. I am trying to build a similar architecture (as yours in the attached image) purely for 3d point cloud reconstruction. My main concern is the absence of a Graph Unpooling layer in the decoder. 

Having done Global Mean Pooling in the encoder, let's say I get a vector of (batch_size, 128) and my original point cloud count is 5000. Would it be correct to up-sample by using **nn.Linear(128,128*5000)** and then reshaping into **(batch_size, 5000,128)** ?  I am a bit new to Graph Networks, I am able to use Message Passing for node dimensions change and Graph Pooling techniques such as SAGPool for down-sampling, my main obstacle is the decoding part where I have to up-scale the latent vectors again using either de-convolution or up-sampling hence the reason I am asking.  Thanks in advance ! 

![Deformable Architecture](https://user-images.githubusercontent.com/51477305/87053334-841a5080-c20a-11ea-9629-44495137a30b.png)

**Comment by orlitany** [comment]
Hi @ahariri13 thanks for your question. Indeed the "unpooling" we used in the paper was a naive linear operation. At the time, due to the lack of a better tool. Note that since our learned shape space is deforming a template of fixed triangulation, there's no inherent problems except that the operator is memory inefficient. I'm happy to hear if you had success replacing it with one of the recent advanced methods for graph unpooling.

**Comment by 2260797779** [comment]
Hi @orlitany :

Thanks for your reply on the decoding part of the model. I'm also trying to implement the GVAE architecture proposed in the paper and have a problem with the "naive linear unpooling operation" mentioned above:

Suppose the batchsize is 1. Let **z** with size(1,128) be the latent vector sample from q(z|x) (or p(z) when generating), and let **F** with size(3446,128) be the unpooled feature map. We have
**F**[i,128] = c<sub>i</sub> * **z**, where c<sub>i</sub> is a learnable scalar 
or
**F**[i,128] = **c**<sub>i</sub> ⨀ **z**, where **c**<sub>i</sub> is a learnable vector with size(1,128) and ⨀ denotes Hadamard product?

Thank you!
